function init(self)
	--	go.animate(".", "rotation", go.PLAYBACK_ONCE_FORWARD, vmath.quat_rotation_y(math.pi), go.EASING_LINEAR, 5)
	self.m_rotateY = 0
end

function final(self)
end

function update(self, dt)
	self.m_rotateY = self.m_rotateY + dt
	local rotation = vmath.quat_rotation_y(self.m_rotateY)
	go.set_rotation(rotation)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
