require("main.common.MiscUtil")

function init(self)
	local node1 = gui.get_node("box1")
	local node2 = gui.get_node("box2")
	local color1 = gui.get_color(node1)
	local color2 = gui.get_color(node2)
	ccprint("gwjgwj,node1=%s,node2=%s", tostring(color1), tostring(color2))
	local textNode = gui.new_text_node(vmath.vector3(display.cx, display.cy, 0), "test")

	local box = gui.get_node("box")
	local newNode = gui.clone(box)
	local pos = gui.get_position(newNode)

--	gui.animate(node1, gui.PROP_COLOR, vmath.vector4(0, 1, 0, 0), gui.EASING_INQUAD, 2, 1.0, function()
--		ccprint("gwjgwj,animation end")
--	end, gui.PLAYBACK_LOOP_PINGPONG)

	gui.set_color(node1, vmath.vector4(0, 1, 0, 0.5))
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
