/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xishanju_defold_cocosext_LuaJavaBridge */

#ifndef _Included_com_xishanju_defold_cocosext_LuaJavaBridge
#define _Included_com_xishanju_defold_cocosext_LuaJavaBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xishanju_defold_cocosext_LuaJavaBridge
 * Method:    callLuaFunctionWithString
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xishanju_defold_cocosext_LuaJavaBridge_callLuaFunctionWithString
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_xishanju_defold_cocosext_LuaJavaBridge
 * Method:    callLuaGlobalFunctionWithString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_xishanju_defold_cocosext_LuaJavaBridge_callLuaGlobalFunctionWithString
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_xishanju_defold_cocosext_LuaJavaBridge
 * Method:    retainLuaFunction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xishanju_defold_cocosext_LuaJavaBridge_retainLuaFunction
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xishanju_defold_cocosext_LuaJavaBridge
 * Method:    releaseLuaFunction
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xishanju_defold_cocosext_LuaJavaBridge_releaseLuaFunction
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xishanju_defold_cocosext_LuaJavaBridge
 * Method:    getMainActivity
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_com_xishanju_defold_cocosext_LuaJavaBridge_getMainActivity
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
