require("main.common.MiscUtil")
local dirtylarry = require("gooey.themes.dirtylarry.dirtylarry")

local function goBack()
	msg.post("main:/go", "showMainScene")
end

function init(self)
	dirtylarry.acquire_input()
end

function final(self)
end

function update(self, dt)
end

function on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
--	ccprint("gwjgwj,on_input:%s", tostring(action_id))
	if(action_id == hash("key_escape") and action.released) then
		goBack()
	end
	local group = dirtylarry.group("group1", function()
		dirtylarry.button("back", action_id, action, function(button)
			goBack()
		end)
	end)
	return group.consumed
end

function on_reload(self)
end
