require("main.common.MiscUtil")
local gwjui = require("gwjui.gwjui")

local function goBack()
	msg.post("main:/go", "showMainScene")
end

function init(self)
	msg.post(".", "acquire_input_focus")
	self.m_input = gwjui.input.createInstance()

	local btnBack = gwjui.ScaleButton.new({
		main_id = "back/bg",
		maxScale = 1.1,
	})
	:onButtonClicked(function()
		goBack()
	end)
end

function final(self)
	self.m_input:final()
end

function update(self, dt)
	self.m_input:onUpdate(dt)
end

function on_message(self, message_id, message, sender)
	self.m_input:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	self.m_input:onInput(action_id, action)
	if(action_id == hash("key_escape") and action.released) then
		goBack()
	end
end

function on_reload(self)
end
