require("main.common.MiscUtil")
local gwjui = require("gwjui.gwjui")

function init(self)
	msg.post(".", "acquire_input_focus")
	self.m_input = gwjui.input.createInstance()
	ccprint("client=%s", tostring(socket))

	local btnRequest = gwjui.ScaleButton.new({
		main_id = "request/bg",
		maxScale = 1.1,
	})
	:onButtonClicked(function()
		doRequest(self)
	end)
end

function final(self)
	self.m_input:final()
end

function update(self, dt)
	self.m_input:onUpdate(dt)
end

function on_message(self, message_id, message, sender)
	self.m_input:on_message(message_id, message, sender)
end

function on_input(self, action_id, action)
	self.m_input:onInput(action_id, action)
end

function on_reload(self)
end

function doRequest(self)
	local url = "https://blog.csdn.net/sobeautiy/article/details/49748545"
	http.request(url, "POST", function(self, _, response)
--		dump(response, "response", 1000)
		if(response.status == 200) then
			local resp = response.response
			local max = 1000
			if(string.len(resp) > max) then
				resp = string.sub(resp, 1, max)
			end
			ccprint("gwjgwj,response=%s", resp)
			local node = gui.get_node("text")
			gui.set_text(node, resp)
		end
	end)
end
