require("main.common.MiscUtil")

function init(self)
	print("test01.init")
	msg.post(".", "acquire_input_focus")--关键
	self.m_moveRight = true
	self.m_move = false
	local width = display.width
	local height = display.height
	print(string.format("wh:%d,%d", width, height))
end

function final(self)
	print("test01.final")
end

function update(self, dt)
	--	print("test01.update")
	if(self.m_move) then
		local pos = go.get_position()
		local speed = dt * 30
		if(self.m_moveRight) then
			pos.x = pos.x + speed
			if(pos.x > display.width) then
				pos.x = display.width
				self.m_moveRight = not self.m_moveRight
			end
		else
			pos.x = pos.x - speed
			if(pos.x < 0) then
				pos.x = 0
				self.m_moveRight = not self.m_moveRight
			end
		end
		go.set_position(pos)
	end
end

function on_message(self, message_id, message, sender)
	print("test01.on_message")
end

function on_input(self, action_id, action)
	if(action_id) then
		ccprint("test01.on_input,action_id=%s,self=%s", tostring(action_id), tostring(self))
--		if(action_id == hash("abcde")) then
--			print("on_input:abcde")
--		end
	end
end

function on_reload(self)
	print("test01.on_reload")
end
